source "https://rubygems.org"

gem "html_truncator"
gem "middleman", "~> 4.2"
gem "middleman-dato"
gem "middleman-livereload"
gem "middleman-minify-html"
gem "middleman-paginate"
gem "middleman-search_engine_sitemap"
gem "middleman-svg"
gem "pry"
gem "redcarpet"
gem "slim"
